CREATE DATABASE LINK gazfond_fondb
CONNECT TO gazfond IDENTIFIED BY mju7ygvfr$
USING '(DESCRIPTION = (ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = 10.1.1.117)(PORT = 1521))) (CONNECT_DATA = (SERVICE_NAME=fonddb)))'
/
CREATE DATABASE LINK fnd_fondb
CONNECT TO fnd IDENTIFIED BY "3edc>lo9"
USING '(DESCRIPTION = (ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = 10.1.1.117)(PORT = 1521))) (CONNECT_DATA = (SERVICE_NAME=fonddb)))'
/
