create or replace view gf_idcards_v as
  select ic.id,
         ic.fk_person,
         ic.fk_idcard_type,
         ic.state,
         ic.lastname,
         ic.firstname,
         ic.secondname,
         ic.birthdate,
         ic.birthplace,
         ic.gender,
         ic.series,
         ic.nbr,
         ic.issued,
         ic.authority,
         ic.authority_code,
         ic.fk_registration_address,
         ic.nationality,
         ic.commentary,
         ic.last_update,
         ic.creation_date,
         ic.fk_document,
         ic.fk_operator,
         ic.change_date,
         ic.migration_card_serial_number,
         ic.migration_card_start_date,
         ic.migration_card_end_date,
         ic.permission_id_card_type,
         ic.permission_series,
         ic.permission_number,
         ic.permission_start_date,
         ic.permission_end_date,
         ic.citizenship,
         ic.fk_first_operator,
         ic.fk_doc_identity
  from   gazfond.idcards ic
/
