select 'drop ' || o.OBJECT_TYPE || ' ' || o.OBJECT_NAME || ';' cmd_drop,
       o.*
from   user_objects o
where  object_type not in ('INDEX', 'PACKAGE BODY', 'SEQUENCE')
and    object_name not in (
'CASH_FLOW_CORRECTS_T',
'DV_SR_LSPV_CORRECTION_T',
'DV_SR_LSPV_CORR_T',
'F6NDFL_LOAD_SPRAVKI',
'F6NDFL_LOAD_SUMGOD',
'F6NDFL_LOAD_SUMPOSTAVKE',
'F6NDFL_LOAD_SVED',
'FIZ_LITS_LSPV_ALL',
'F_NDFL_LOAD_SPISRAB',
'ZAPRVKL_CROSS_T',
'ZAPRVKL_HEADERS_T',
'ZAPRVKL_LINES_T',
'ZAPRVKL_LINES_TMP'
)
order by object_type, object_name
/
/* --get ddl
select o.OBJECT_NAME, o.OBJECT_TYPE, DBMS_METADATA.GET_DDL(o.OBJECT_TYPE, o.OBJECT_NAME)
from   user_objects o
where  object_type = 'VIEW' --not in ('INDEX', 'PACKAGE BODY', 'SEQUENCE')
and    object_name not in (
'CASH_FLOW_CORRECTS_T',
'DV_SR_LSPV_CORRECTION_T',
'DV_SR_LSPV_CORR_T',
'F6NDFL_LOAD_SPRAVKI',
'F6NDFL_LOAD_SUMGOD',
'F6NDFL_LOAD_SUMPOSTAVKE',
'F6NDFL_LOAD_SVED',
'FIZ_LITS_LSPV_ALL',
'F_NDFL_LOAD_SPISRAB',
'ZAPRVKL_CROSS_T',
'ZAPRVKL_HEADERS_T',
'ZAPRVKL_LINES_T',
'ZAPRVKL_LINES_TMP'
)
order by object_type, object_name
--*/
/* 
исключения при очистке схемы
CASH_FLOW_CORRECTS_T, --table
DV_SR_LSPV_CORRECTION_T, --table
DV_SR_LSPV_CORR_T, --table
F6NDFL_LOAD_SPRAVKI,
F6NDFL_LOAD_SUMGOD,
F6NDFL_LOAD_SUMPOSTAVKE,
F6NDFL_LOAD_SVED,
FIZ_LITS_LSPV_ALL,
F_NDFL_LOAD_SPISRAB,
ZAPRVKL_CROSS_T,
ZAPRVKL_HEADERS_T,
ZAPRVKL_LINES_T,
ZAPRVKL_LINES_TMP
*/
